# Generated by Django 4.0.4 on 2022-05-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampledata',
            name='_id',
        ),
    ]
