# Generated by Django 4.0.4 on 2022-05-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniProject', '0003_alter_sampledata_total_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledata',
            name='patch_state',
            field=models.CharField(default='running', max_length=100),
        ),
    ]
