# Generated by Django 4.0.4 on 2022-05-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniProject', '0004_sampledata_patch_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='branch',
            field=models.CharField(default='BTHT1', max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='function',
            field=models.CharField(default='SW-FTI-BB', max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='hostname',
            field=models.CharField(default='HNIB03405HW50', max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='ip',
            field=models.CharField(default='10.41.2.28', max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='model',
            field=models.CharField(default='HW50', max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='number_of_pop_tail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='patch_ver',
            field=models.CharField(default='s5720si-v200r011sph007', max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='pop',
            field=models.CharField(default='HNIB034', max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='province',
            field=models.CharField(default='HNI', max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='sep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='smart_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='software_ver',
            field=models.CharField(default='S5720 V200R011C10SPC600', max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='stack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='switch_type',
            field=models.CharField(default='S5720-28X-', max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='total_mac',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='type',
            field=models.CharField(default='HUAWEI', max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='zone',
            field=models.IntegerField(default=1),
        ),
    ]
